---
- name: Ansible lab
  # TODO: change to remote if you have one
  hosts: local
  gather_facts: true

  tasks:
    # Use {{ aptcachetime }} variable to specify cache time
    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#examples
    - name: Install some basic packages defined in variable "packages"
      become: true
      apt:
        name: '{{ packages }}'
        update_cache: yes
        cache_valid_time: '{{ aptcachetime }}'

    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
    - name: Enable Nginx service, ensure it is not masked and start it
      become: true
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        masked: no

    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples
    # path should be {{ app_dir }}
    # owner should be {{ ansible_user_id }}
    # mode should be 755
    - name: Create {{ app_dir }} directory if it does not exist
      become: true
      ansible.builtin.file:
        path: '{{ app_dir }}'
        owner: '{{ ansible_user_id }}'
        mode: '0755'
        state: directory

    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#examples
    # Download url: https://storage.googleapis.com/devops-practice-files/systemd/ServicesLab-0.0.1.jar
    # dest should be {{ app_dir }}/{{ app_file }}
    # owner should be {{ ansible_user_id }}
    # mode should be 644
    - name: Download Java app to {{ app_dir }}/{{ app_file }}
      ansible.builtin.get_url:
        dest: '{{ app_dir }}/{{ app_file }}'
        owner: '{{ ansible_user_id }}'
        mode: '0644'
        url: https://storage.googleapis.com/devops-practice-files/systemd/ServicesLab-0.0.1.jar

    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#examples
    # dest should be /etc/systemd/system/sample.service
    # source is app.service.j2
    # mode should be 644
    # owner should be root
    # group should be root
    - name: Create a Java App Unit
      become: true
      # To show how handlers work. This happens when you change the template that already exists
      notify:
      - Reload Systemd
      ansible.builtin.template:
        dest: /etc/systemd/system/sample.service
        src: app.service.j2
        mode: '0644'
        owner: root
        group: root

    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
    - name: Enable sample.service, ensure it is not masked and start it
      become: true
      ansible.builtin.systemd:
        daemon_reload: yes
        name: sample
        enabled: yes
        masked: no
        state: started

    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#examples
    # dest should be /etc/nginx/nginx.conf
    # source is nginx.conf.j2
    # mode should be 644
    # owner should be root
    # group should be root
    - name: Create a Nginx config
      become: true
      ansible.builtin.template:
        dest: /etc/nginx/nginx.conf
        src: nginx.conf.j2
        mode: '0644'
        owner: root
        group: root

    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
    - name: Restart Nginx
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: restarted
  
  handlers:
    # Do a daemon reload
    # Find implementation in https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
    - name: Reload Systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: yes